services:
  bot:
    build: .
    container_name: python-bot-scheduler
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - SCHEDULES_DB_PATH=/data/schedules.db
    volumes:
      - ./schedules.db:/data/schedules.db

